// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Element {
    "Name": string;
    "DisplayName": string;
    "Active": boolean;
    "Index": number;
    "IsCustom": boolean;
}
