// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";

export function ActivateElement(n: string): $CancellablePromise<number> {
    return $Call.ByID(3632662009, n);
}

export function AddFPSLimit(amount: string): $CancellablePromise<void> {
    return $Call.ByID(2769033243, amount);
}

export function AddUnorderedElement(name: string): $CancellablePromise<void> {
    return $Call.ByID(2782652917, name);
}

export function ApplyPresetDefault(): $CancellablePromise<void> {
    return $Call.ByID(810049750);
}

export function ApplyPresetExtended(): $CancellablePromise<void> {
    return $Call.ByID(1225113368);
}

export function ApplyPresetFpsOnly(): $CancellablePromise<void> {
    return $Call.ByID(2305792930);
}

export function ApplyPresetFull(): $CancellablePromise<void> {
    return $Call.ByID(1562353108);
}

export function ApplyPresetMinimal(): $CancellablePromise<void> {
    return $Call.ByID(3526193176);
}

export function ApplyPresetRiva(): $CancellablePromise<void> {
    return $Call.ByID(3401719053);
}

export function DeactivateElement(n: string): $CancellablePromise<void> {
    return $Call.ByID(1189972188, n);
}

export function DisableGlobally(): $CancellablePromise<void> {
    return $Call.ByID(2597548178);
}

export function EnableGlobally(): $CancellablePromise<void> {
    return $Call.ByID(3750206205);
}

export function GetBackgroundAlpha(): $CancellablePromise<string> {
    return $Call.ByID(3135902714);
}

export function GetBackgroundColor(): $CancellablePromise<string> {
    return $Call.ByID(1870042133);
}

export function GetBatteryColor(): $CancellablePromise<string> {
    return $Call.ByID(2940617034);
}

export function GetCpuColor(): $CancellablePromise<string> {
    return $Call.ByID(2501371483);
}

export function GetCpuElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(2262397501);
}

export function GetCpuLoadColor0(): $CancellablePromise<string> {
    return $Call.ByID(1528093645);
}

export function GetCpuLoadColor1(): $CancellablePromise<string> {
    return $Call.ByID(1511316026);
}

export function GetCpuLoadColor2(): $CancellablePromise<string> {
    return $Call.ByID(1494538407);
}

export function GetCpuLoadValue(): $CancellablePromise<string> {
    return $Call.ByID(3391244841);
}

export function GetCpuText(): $CancellablePromise<string> {
    return $Call.ByID(1559162531);
}

export function GetElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(1518959163);
}

export function GetEngineColor(): $CancellablePromise<string> {
    return $Call.ByID(2699979519);
}

export function GetExtraElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(125953713);
}

export function GetFPSLimits(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4182137909);
}

export function GetFontSize(): $CancellablePromise<string> {
    return $Call.ByID(4049627938);
}

export function GetFpsLoadColor0(): $CancellablePromise<string> {
    return $Call.ByID(2713722468);
}

export function GetFpsLoadColor1(): $CancellablePromise<string> {
    return $Call.ByID(2730500087);
}

export function GetFpsLoadColor2(): $CancellablePromise<string> {
    return $Call.ByID(2747277706);
}

export function GetFpsLoadValue(): $CancellablePromise<string> {
    return $Call.ByID(1219448582);
}

export function GetFrametimeColor(): $CancellablePromise<string> {
    return $Call.ByID(1542157069);
}

export function GetGpuColor(): $CancellablePromise<string> {
    return $Call.ByID(1581105055);
}

export function GetGpuElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(1464312889);
}

export function GetGpuLoadColor0(): $CancellablePromise<string> {
    return $Call.ByID(971540001);
}

export function GetGpuLoadColor1(): $CancellablePromise<string> {
    return $Call.ByID(954762382);
}

export function GetGpuLoadColor2(): $CancellablePromise<string> {
    return $Call.ByID(937984763);
}

export function GetGpuLoadValue(): $CancellablePromise<string> {
    return $Call.ByID(776318397);
}

export function GetGpuText(): $CancellablePromise<string> {
    return $Call.ByID(1228659087);
}

export function GetGraphCpuLoad(): $CancellablePromise<boolean> {
    return $Call.ByID(494666272);
}

export function GetGraphCpuTemp(): $CancellablePromise<boolean> {
    return $Call.ByID(1804631466);
}

export function GetGraphGpuCoreClock(): $CancellablePromise<boolean> {
    return $Call.ByID(2514540763);
}

export function GetGraphGpuLoad(): $CancellablePromise<boolean> {
    return $Call.ByID(2776492204);
}

export function GetGraphGpuMemClock(): $CancellablePromise<boolean> {
    return $Call.ByID(1174934209);
}

export function GetGraphGpuTemp(): $CancellablePromise<boolean> {
    return $Call.ByID(2375070534);
}

export function GetGraphRam(): $CancellablePromise<boolean> {
    return $Call.ByID(3594059666);
}

export function GetGraphVram(): $CancellablePromise<boolean> {
    return $Call.ByID(290447596);
}

export function GetIoColor(): $CancellablePromise<string> {
    return $Call.ByID(4046818941);
}

export function GetKbReloadCfg(): $CancellablePromise<string> {
    return $Call.ByID(1221591384);
}

export function GetKbToggleFpsLimit(): $CancellablePromise<string> {
    return $Call.ByID(505572805);
}

export function GetKbToggleHud(): $CancellablePromise<string> {
    return $Call.ByID(2317308620);
}

export function GetKbToggleHudPosition(): $CancellablePromise<string> {
    return $Call.ByID(3877026351);
}

export function GetKbToggleLogging(): $CancellablePromise<string> {
    return $Call.ByID(1067076336);
}

export function GetKbTogglePreset(): $CancellablePromise<string> {
    return $Call.ByID(2118039816);
}

export function GetKbUploadLog(): $CancellablePromise<string> {
    return $Call.ByID(2362517220);
}

export function GetMediaColor(): $CancellablePromise<string> {
    return $Call.ByID(1955257253);
}

export function GetMemoryElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(3063267604);
}

export function GetNetworkColor(): $CancellablePromise<string> {
    return $Call.ByID(187950823);
}

export function GetOffsetX(): $CancellablePromise<string> {
    return $Call.ByID(2024588151);
}

export function GetOffsetY(): $CancellablePromise<string> {
    return $Call.ByID(2007810532);
}

export function GetOrderElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(4243094179);
}

export function GetOrientation(): $CancellablePromise<string> {
    return $Call.ByID(346961140);
}

export function GetPosition(): $CancellablePromise<string> {
    return $Call.ByID(965248365);
}

export function GetRamColor(): $CancellablePromise<string> {
    return $Call.ByID(3944907277);
}

export function GetRoundCorners(): $CancellablePromise<boolean> {
    return $Call.ByID(2551507968);
}

export function GetTableColumns(): $CancellablePromise<string> {
    return $Call.ByID(3255468829);
}

export function GetTextColor(): $CancellablePromise<string> {
    return $Call.ByID(889783036);
}

export function GetTextOutlineColor(): $CancellablePromise<string> {
    return $Call.ByID(1267118588);
}

export function GetTextOutlineThickness(): $CancellablePromise<string> {
    return $Call.ByID(252182409);
}

export function GetUnorderedElements(): $CancellablePromise<config$0.Element[] | null> {
    return $Call.ByID(3481480587);
}

export function GetUseOffset(): $CancellablePromise<boolean> {
    return $Call.ByID(1137745322);
}

export function GetVramColor(): $CancellablePromise<string> {
    return $Call.ByID(3632023499);
}

export function GetWineColor(): $CancellablePromise<string> {
    return $Call.ByID(2322692178);
}

export function GloballyEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(736795159);
}

export function ImportConfig(s: string): $CancellablePromise<void> {
    return $Call.ByID(3027425097, s);
}

export function OpenLink(url: string): $CancellablePromise<void> {
    return $Call.ByID(2420141006, url);
}

export function OrderElementUnderneathElement(toOrder: string, underneath: string): $CancellablePromise<void> {
    return $Call.ByID(1450061008, toOrder, underneath);
}

export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(1164952377);
}

export function RemoveFPSLimit(index: number): $CancellablePromise<void> {
    return $Call.ByID(1025038276, index);
}

export function RemoveUnorderedElement(index: number): $CancellablePromise<void> {
    return $Call.ByID(2982300090, index);
}

export function ReorderFPSLimit(firstIndex: number, secondIndex: number): $CancellablePromise<void> {
    return $Call.ByID(434229795, firstIndex, secondIndex);
}

export function ReplaceElements(first: string, second: string): $CancellablePromise<void> {
    return $Call.ByID(1554193643, first, second);
}

export function ResetConfig(): $CancellablePromise<void> {
    return $Call.ByID(1266325995);
}

export function RestartVkcube(): $CancellablePromise<void> {
    return $Call.ByID(1653324671);
}

export function SetBackgroundAlpha(n: string): $CancellablePromise<void> {
    return $Call.ByID(1687626078, n);
}

export function SetBackgroundColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(962948265, n);
}

export function SetBatteryColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(2229883206, n);
}

export function SetCpuColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(3270126311, n);
}

export function SetCpuLoadColors(n0: string, n1: string, n2: string): $CancellablePromise<void> {
    return $Call.ByID(1134123392, n0, n1, n2);
}

export function SetCpuLoadValue(n: string): $CancellablePromise<void> {
    return $Call.ByID(2032731269, n);
}

export function SetCpuText(n: string): $CancellablePromise<void> {
    return $Call.ByID(1985801127, n);
}

export function SetEngineColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(3182432179, n);
}

export function SetFontSize(n: string): $CancellablePromise<void> {
    return $Call.ByID(711367014, n);
}

export function SetFpsLoadColors(n0: string, n1: string, n2: string): $CancellablePromise<void> {
    return $Call.ByID(2723011369, n0, n1, n2);
}

export function SetFpsLoadValue(n: string): $CancellablePromise<void> {
    return $Call.ByID(2058849970, n);
}

export function SetFrametimeColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(2137360049, n);
}

export function SetGpuColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(3442403683, n);
}

export function SetGpuLoadColors(n0: string, n1: string, n2: string): $CancellablePromise<void> {
    return $Call.ByID(408559244, n0, n1, n2);
}

export function SetGpuLoadValue(n: string): $CancellablePromise<void> {
    return $Call.ByID(131408689, n);
}

export function SetGpuText(n: string): $CancellablePromise<void> {
    return $Call.ByID(37801979, n);
}

export function SetIoColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(4084045249, n);
}

export function SetKbReloadCfg(n: string): $CancellablePromise<void> {
    return $Call.ByID(3192020284, n);
}

export function SetKbToggleFpsLimit(n: string): $CancellablePromise<void> {
    return $Call.ByID(41554577, n);
}

export function SetKbToggleHud(n: string): $CancellablePromise<void> {
    return $Call.ByID(1301363952, n);
}

export function SetKbToggleHudPosition(n: string): $CancellablePromise<void> {
    return $Call.ByID(1338174835, n);
}

export function SetKbToggleLogging(n: string): $CancellablePromise<void> {
    return $Call.ByID(2724626708, n);
}

export function SetKbTogglePreset(n: string): $CancellablePromise<void> {
    return $Call.ByID(3267459228, n);
}

export function SetKbUploadLog(n: string): $CancellablePromise<void> {
    return $Call.ByID(3069781248, n);
}

export function SetMediaColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(3824223249, n);
}

export function SetNetworkColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(2426782419, n);
}

export function SetOffsetX(n: string): $CancellablePromise<void> {
    return $Call.ByID(260908979, n);
}

export function SetOffsetY(n: string): $CancellablePromise<void> {
    return $Call.ByID(244131360, n);
}

export function SetOrientation(n: string): $CancellablePromise<void> {
    return $Call.ByID(4164917776, n);
}

export function SetPosition(n: string): $CancellablePromise<void> {
    return $Call.ByID(3515315849, n);
}

export function SetRamColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(4189789577, n);
}

export function SetRoundedCorners(n: boolean): $CancellablePromise<void> {
    return $Call.ByID(2412611207, n);
}

export function SetTableColumns(n: string): $CancellablePromise<void> {
    return $Call.ByID(2462447865, n);
}

export function SetTextColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(3715452608, n);
}

export function SetTextOutlineColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(439557224, n);
}

export function SetTextOutlineThickness(n: string): $CancellablePromise<void> {
    return $Call.ByID(2204039013, n);
}

export function SetUseOffset(n: boolean): $CancellablePromise<void> {
    return $Call.ByID(4145920662, n);
}

export function SetVramColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(1970796551, n);
}

export function SetWineColor(n: string): $CancellablePromise<void> {
    return $Call.ByID(2161721958, n);
}

export function ShareConfig(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1094557647);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3847134920);
}

export function StartVkcube(): $CancellablePromise<void> {
    return $Call.ByID(2113430380);
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(3127193451);
}

export function StopVkcube(): $CancellablePromise<void> {
    return $Call.ByID(3972002532);
}

export function ToggleGraphCpuLoad(): $CancellablePromise<void> {
    return $Call.ByID(823369396);
}

export function ToggleGraphCpuTemp(): $CancellablePromise<void> {
    return $Call.ByID(3742530718);
}

export function ToggleGraphGpuCoreClock(): $CancellablePromise<void> {
    return $Call.ByID(3037816023);
}

export function ToggleGraphGpuLoad(): $CancellablePromise<void> {
    return $Call.ByID(3591245160);
}

export function ToggleGraphGpuMemClock(): $CancellablePromise<void> {
    return $Call.ByID(3666305949);
}

export function ToggleGraphGpuTemp(): $CancellablePromise<void> {
    return $Call.ByID(3809280002);
}

export function ToggleGraphRam(): $CancellablePromise<void> {
    return $Call.ByID(588540990);
}

export function ToggleGraphVram(): $CancellablePromise<void> {
    return $Call.ByID(2882491512);
}

export function UpdateFPSLimit(index: number, amount: string): $CancellablePromise<void> {
    return $Call.ByID(3398607205, index, amount);
}
