// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackgroundAlpha():Promise<string>;

export function GetBackgroundColor():Promise<string>;

export function GetFontSize():Promise<string>;

export function GetOrientation():Promise<string>;

export function GetRoundCorners():Promise<boolean>;

export function ResetConfig():Promise<void>;

export function RestartVkcube():Promise<void>;

export function SetBackgroundAlpha(arg1:string):Promise<void>;

export function SetBackgroundColor(arg1:string):Promise<void>;

export function SetFontSize(arg1:string):Promise<void>;

export function SetOrientation(arg1:string):Promise<void>;

export function SetRoundedCorners(arg1:boolean):Promise<void>;
