// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ActivateElement(arg1:string):Promise<number>;

export function AddFPSLimit(arg1:string):Promise<void>;

export function DeactivateElement(arg1:string):Promise<void>;

export function DisableGlobally():Promise<void>;

export function EnableGlobally():Promise<void>;

export function GetBackgroundAlpha():Promise<string>;

export function GetBackgroundColor():Promise<string>;

export function GetBatteryColor():Promise<string>;

export function GetCpuColor():Promise<string>;

export function GetCpuElements():Promise<Array<config.Element>>;

export function GetCpuLoadColor0():Promise<string>;

export function GetCpuLoadColor1():Promise<string>;

export function GetCpuLoadColor2():Promise<string>;

export function GetCpuLoadValue():Promise<string>;

export function GetCpuText():Promise<string>;

export function GetElements():Promise<Array<config.Element>>;

export function GetEngineColor():Promise<string>;

export function GetExtraElements():Promise<Array<config.Element>>;

export function GetFPSLimits():Promise<Array<config.FPSLimit>>;

export function GetFontSize():Promise<string>;

export function GetFrametimeColor():Promise<string>;

export function GetGpuColor():Promise<string>;

export function GetGpuElements():Promise<Array<config.Element>>;

export function GetGpuLoadColor0():Promise<string>;

export function GetGpuLoadColor1():Promise<string>;

export function GetGpuLoadColor2():Promise<string>;

export function GetGpuLoadValue():Promise<string>;

export function GetGpuText():Promise<string>;

export function GetIoColor():Promise<string>;

export function GetKbReloadCfg():Promise<string>;

export function GetKbToggleFpsLimit():Promise<string>;

export function GetKbToggleHud():Promise<string>;

export function GetKbToggleHudPosition():Promise<string>;

export function GetKbToggleLogging():Promise<string>;

export function GetKbTogglePreset():Promise<string>;

export function GetKbUploadLog():Promise<string>;

export function GetMediaColor():Promise<string>;

export function GetMemoryElements():Promise<Array<config.Element>>;

export function GetNetworkColor():Promise<string>;

export function GetOrientation():Promise<string>;

export function GetPosition():Promise<string>;

export function GetRamColor():Promise<string>;

export function GetRoundCorners():Promise<boolean>;

export function GetTextColor():Promise<string>;

export function GetVramColor():Promise<string>;

export function GetWineColor():Promise<string>;

export function GloballyEnabled():Promise<boolean>;

export function RemoveFPSLimit(arg1:number):Promise<void>;

export function ReorderFPSLimit(arg1:number,arg2:number):Promise<void>;

export function ReplaceElements(arg1:string,arg2:string):Promise<void>;

export function ResetConfig():Promise<void>;

export function RestartVkcube():Promise<void>;

export function SetBackgroundAlpha(arg1:string):Promise<void>;

export function SetBackgroundColor(arg1:string):Promise<void>;

export function SetBatteryColor(arg1:string):Promise<void>;

export function SetCpuColor(arg1:string):Promise<void>;

export function SetCpuLoadColors(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetCpuLoadValue(arg1:string):Promise<void>;

export function SetCpuText(arg1:string):Promise<void>;

export function SetEngineColor(arg1:string):Promise<void>;

export function SetFontSize(arg1:string):Promise<void>;

export function SetFrametimeColor(arg1:string):Promise<void>;

export function SetGpuColor(arg1:string):Promise<void>;

export function SetGpuLoadColors(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetGpuLoadValue(arg1:string):Promise<void>;

export function SetGpuText(arg1:string):Promise<void>;

export function SetIoColor(arg1:string):Promise<void>;

export function SetKbReloadCfg(arg1:string):Promise<void>;

export function SetKbToggleFpsLimit(arg1:string):Promise<void>;

export function SetKbToggleHud(arg1:string):Promise<void>;

export function SetKbToggleHudPosition(arg1:string):Promise<void>;

export function SetKbToggleLogging(arg1:string):Promise<void>;

export function SetKbTogglePreset(arg1:string):Promise<void>;

export function SetKbUploadLog(arg1:string):Promise<void>;

export function SetMediaColor(arg1:string):Promise<void>;

export function SetNetworkColor(arg1:string):Promise<void>;

export function SetOrientation(arg1:string):Promise<void>;

export function SetPosition(arg1:string):Promise<void>;

export function SetRamColor(arg1:string):Promise<void>;

export function SetRoundedCorners(arg1:boolean):Promise<void>;

export function SetTextColor(arg1:string):Promise<void>;

export function SetVramColor(arg1:string):Promise<void>;

export function SetWineColor(arg1:string):Promise<void>;

export function StartVkcube():Promise<void>;

export function StopVkcube():Promise<void>;
