// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackgroundAlpha() {
  return window['go']['main']['App']['GetBackgroundAlpha']();
}

export function GetBackgroundColor() {
  return window['go']['main']['App']['GetBackgroundColor']();
}

export function GetBatteryColor() {
  return window['go']['main']['App']['GetBatteryColor']();
}

export function GetCpuColor() {
  return window['go']['main']['App']['GetCpuColor']();
}

export function GetCpuLoadColor0() {
  return window['go']['main']['App']['GetCpuLoadColor0']();
}

export function GetCpuLoadColor1() {
  return window['go']['main']['App']['GetCpuLoadColor1']();
}

export function GetCpuLoadColor2() {
  return window['go']['main']['App']['GetCpuLoadColor2']();
}

export function GetEngineColor() {
  return window['go']['main']['App']['GetEngineColor']();
}

export function GetFontSize() {
  return window['go']['main']['App']['GetFontSize']();
}

export function GetFrametimeColor() {
  return window['go']['main']['App']['GetFrametimeColor']();
}

export function GetGpuColor() {
  return window['go']['main']['App']['GetGpuColor']();
}

export function GetGpuLoadChange() {
  return window['go']['main']['App']['GetGpuLoadChange']();
}

export function GetGpuLoadColor0() {
  return window['go']['main']['App']['GetGpuLoadColor0']();
}

export function GetGpuLoadColor1() {
  return window['go']['main']['App']['GetGpuLoadColor1']();
}

export function GetGpuLoadColor2() {
  return window['go']['main']['App']['GetGpuLoadColor2']();
}

export function GetGpuText() {
  return window['go']['main']['App']['GetGpuText']();
}

export function GetIoColor() {
  return window['go']['main']['App']['GetIoColor']();
}

export function GetKbReloadCfg() {
  return window['go']['main']['App']['GetKbReloadCfg']();
}

export function GetKbToggleFpsLimit() {
  return window['go']['main']['App']['GetKbToggleFpsLimit']();
}

export function GetKbToggleHud() {
  return window['go']['main']['App']['GetKbToggleHud']();
}

export function GetKbToggleHudPosition() {
  return window['go']['main']['App']['GetKbToggleHudPosition']();
}

export function GetKbToggleLogging() {
  return window['go']['main']['App']['GetKbToggleLogging']();
}

export function GetKbTogglePreset() {
  return window['go']['main']['App']['GetKbTogglePreset']();
}

export function GetKbUploadLog() {
  return window['go']['main']['App']['GetKbUploadLog']();
}

export function GetMediaColor() {
  return window['go']['main']['App']['GetMediaColor']();
}

export function GetNetworkColor() {
  return window['go']['main']['App']['GetNetworkColor']();
}

export function GetOrientation() {
  return window['go']['main']['App']['GetOrientation']();
}

export function GetPosition() {
  return window['go']['main']['App']['GetPosition']();
}

export function GetRamColor() {
  return window['go']['main']['App']['GetRamColor']();
}

export function GetRoundCorners() {
  return window['go']['main']['App']['GetRoundCorners']();
}

export function GetTextColor() {
  return window['go']['main']['App']['GetTextColor']();
}

export function GetVramColor() {
  return window['go']['main']['App']['GetVramColor']();
}

export function GetWineColor() {
  return window['go']['main']['App']['GetWineColor']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestartVkcube() {
  return window['go']['main']['App']['RestartVkcube']();
}

export function SetBackgroundAlpha(arg1) {
  return window['go']['main']['App']['SetBackgroundAlpha'](arg1);
}

export function SetBackgroundColor(arg1) {
  return window['go']['main']['App']['SetBackgroundColor'](arg1);
}

export function SetBatteryColor(arg1) {
  return window['go']['main']['App']['SetBatteryColor'](arg1);
}

export function SetCpuColor(arg1) {
  return window['go']['main']['App']['SetCpuColor'](arg1);
}

export function SetCpuLoadColors(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCpuLoadColors'](arg1, arg2, arg3);
}

export function SetEngineColor(arg1) {
  return window['go']['main']['App']['SetEngineColor'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetFrametimeColor(arg1) {
  return window['go']['main']['App']['SetFrametimeColor'](arg1);
}

export function SetGpuColor(arg1) {
  return window['go']['main']['App']['SetGpuColor'](arg1);
}

export function SetGpuLoadChange(arg1) {
  return window['go']['main']['App']['SetGpuLoadChange'](arg1);
}

export function SetGpuLoadColors(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGpuLoadColors'](arg1, arg2, arg3);
}

export function SetGpuText(arg1) {
  return window['go']['main']['App']['SetGpuText'](arg1);
}

export function SetIoColor(arg1) {
  return window['go']['main']['App']['SetIoColor'](arg1);
}

export function SetKbReloadCfg(arg1) {
  return window['go']['main']['App']['SetKbReloadCfg'](arg1);
}

export function SetKbToggleFpsLimit(arg1) {
  return window['go']['main']['App']['SetKbToggleFpsLimit'](arg1);
}

export function SetKbToggleHud(arg1) {
  return window['go']['main']['App']['SetKbToggleHud'](arg1);
}

export function SetKbToggleHudPosition(arg1) {
  return window['go']['main']['App']['SetKbToggleHudPosition'](arg1);
}

export function SetKbToggleLogging(arg1) {
  return window['go']['main']['App']['SetKbToggleLogging'](arg1);
}

export function SetKbTogglePreset(arg1) {
  return window['go']['main']['App']['SetKbTogglePreset'](arg1);
}

export function SetKbUploadLog(arg1) {
  return window['go']['main']['App']['SetKbUploadLog'](arg1);
}

export function SetMediaColor(arg1) {
  return window['go']['main']['App']['SetMediaColor'](arg1);
}

export function SetNetworkColor(arg1) {
  return window['go']['main']['App']['SetNetworkColor'](arg1);
}

export function SetOrientation(arg1) {
  return window['go']['main']['App']['SetOrientation'](arg1);
}

export function SetPosition(arg1) {
  return window['go']['main']['App']['SetPosition'](arg1);
}

export function SetRamColor(arg1) {
  return window['go']['main']['App']['SetRamColor'](arg1);
}

export function SetRoundedCorners(arg1) {
  return window['go']['main']['App']['SetRoundedCorners'](arg1);
}

export function SetTextColor(arg1) {
  return window['go']['main']['App']['SetTextColor'](arg1);
}

export function SetVramColor(arg1) {
  return window['go']['main']['App']['SetVramColor'](arg1);
}

export function SetWineColor(arg1) {
  return window['go']['main']['App']['SetWineColor'](arg1);
}
