// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackgroundAlpha() {
  return window['go']['main']['App']['GetBackgroundAlpha']();
}

export function GetBackgroundColor() {
  return window['go']['main']['App']['GetBackgroundColor']();
}

export function GetFontSize() {
  return window['go']['main']['App']['GetFontSize']();
}

export function GetOrientation() {
  return window['go']['main']['App']['GetOrientation']();
}

export function GetRoundCorners() {
  return window['go']['main']['App']['GetRoundCorners']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestartVkcube() {
  return window['go']['main']['App']['RestartVkcube']();
}

export function SetBackgroundAlpha(arg1) {
  return window['go']['main']['App']['SetBackgroundAlpha'](arg1);
}

export function SetBackgroundColor(arg1) {
  return window['go']['main']['App']['SetBackgroundColor'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetOrientation(arg1) {
  return window['go']['main']['App']['SetOrientation'](arg1);
}

export function SetRoundedCorners(arg1) {
  return window['go']['main']['App']['SetRoundedCorners'](arg1);
}
