// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOrientation():Promise<string>;

export function GetRoundCorners():Promise<boolean>;

export function SetOrientation(arg1:string):Promise<void>;

export function SetRoundedCorners(arg1:boolean):Promise<void>;
